#!/usr/bin/env python3
"""Generate src/tokenizer/unicode_tables.h from the Python stdlib Unicode data.

The from-scratch BPE pre-tokenizer (src/tokenizer/bpe.cpp) replicates the
Llama-3.2 Split regex, which uses the Unicode property classes \\p{L} (Letter)
and \\p{N} (Number) and the whitespace class \\s. std::regex cannot evaluate
those classes, and we deliberately avoid adding a Unicode/regex dependency, so
this script bakes the classification into sorted codepoint-range tables that the
C++ side resolves with a binary search.

  \\p{L} -> Unicode general categories Lu, Ll, Lt, Lm, Lo  (category starts 'L')
  \\p{N} -> Unicode general categories Nd, Nl, No          (category starts 'N')
  \\s    -> the Unicode White_Space property. unicodedata does not expose this
            property directly, so the fixed (and very stable) set is hardcoded
            below; it matches the Rust `regex` crate's \\s used by the reference
            HF tokenizer.

Regenerate (rarely needed — only on a Unicode version bump):

  python3.12 -m venv reference/.venv      # if not already created
  reference/.venv/bin/python reference/gen_unicode_tables.py

The generated header is committed; this script and the venv are not required at
build time.
"""

import sys
import unicodedata
from pathlib import Path

# The Unicode White_Space property (matches Rust regex `\s`). Stable across
# Unicode versions; listed explicitly because unicodedata has no White_Space API.
WHITESPACE = [
    0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x20, 0x85, 0xA0,
    0x1680,
    0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006, 0x2007,
    0x2008, 0x2009, 0x200A,
    0x2028, 0x2029, 0x202F, 0x205F, 0x3000,
]


def collect_ranges(predicate):
    """Sorted list of inclusive [lo, hi] codepoint ranges where predicate holds."""
    ranges = []
    lo = None
    for cp in range(sys.maxunicode + 1):
        if predicate(cp):
            if lo is None:
                lo = cp
            hi = cp
        elif lo is not None:
            ranges.append((lo, hi))
            lo = None
    if lo is not None:
        ranges.append((lo, hi))
    return ranges


def category_starts(letter):
    return lambda cp: unicodedata.category(chr(cp)).startswith(letter)


def to_ranges_from_points(points):
    points = sorted(points)
    ranges = []
    for cp in points:
        if ranges and cp == ranges[-1][1] + 1:
            ranges[-1] = (ranges[-1][0], cp)
        else:
            ranges.append((cp, cp))
    return ranges


def emit_ranges(name, ranges):
    lines = [f"inline constexpr Range {name}[] = {{"]
    row = "  "
    for lo, hi in ranges:
        cell = f"{{0x{lo:04X},0x{hi:04X}}}, "
        if len(row) + len(cell) > 96:
            lines.append(row.rstrip())
            row = "  "
        row += cell
    if row.strip():
        lines.append(row.rstrip())
    lines.append("};")
    return "\n".join(lines)


def main():
    letter = collect_ranges(category_starts("L"))
    number = collect_ranges(category_starts("N"))
    space = to_ranges_from_points(WHITESPACE)

    out = Path(__file__).resolve().parent.parent / "src" / "tokenizer" / "unicode_tables.h"
    uni_version = unicodedata.unidata_version

    parts = []
    parts.append(f"""// GENERATED by reference/gen_unicode_tables.py — DO NOT EDIT BY HAND.
// Unicode version: {uni_version}. Regenerate with:
//   reference/.venv/bin/python reference/gen_unicode_tables.py
//
// Sorted, inclusive codepoint ranges for the Unicode classes the Llama-3.2
// pre-tokenizer regex needs: \\p{{L}} (Letter), \\p{{N}} (Number), and \\s
// (White_Space). Resolved by binary search — see is_letter/is_number/
// is_whitespace below.
#pragma once

#include <cstdint>

namespace mlxforge::unicode {{

struct Range {{
  uint32_t lo;  // inclusive
  uint32_t hi;  // inclusive
}};
""")
    parts.append(emit_ranges("kLetter", letter))
    parts.append("")
    parts.append(emit_ranges("kNumber", number))
    parts.append("")
    parts.append(emit_ranges("kWhitespace", space))
    parts.append("""
// Binary search: is `cp` covered by any range in `table`?
inline bool in_ranges(uint32_t cp, const Range* table, size_t n) {
  size_t lo = 0, hi = n;
  while (lo < hi) {
    size_t mid = lo + (hi - lo) / 2;
    if (cp < table[mid].lo)
      hi = mid;
    else if (cp > table[mid].hi)
      lo = mid + 1;
    else
      return true;
  }
  return false;
}

template <size_t N>
inline bool in_ranges(uint32_t cp, const Range (&table)[N]) {
  return in_ranges(cp, table, N);
}

inline bool is_letter(uint32_t cp) { return in_ranges(cp, kLetter); }      // \\p{L}
inline bool is_number(uint32_t cp) { return in_ranges(cp, kNumber); }      // \\p{N}
inline bool is_whitespace(uint32_t cp) { return in_ranges(cp, kWhitespace); }  // \\s

}  // namespace mlxforge::unicode
""")

    out.write_text("\n".join(parts) + "\n")
    print(f"wrote {out}")
    print(f"  Unicode {uni_version}: kLetter={len(letter)} ranges, "
          f"kNumber={len(number)} ranges, kWhitespace={len(space)} ranges")


if __name__ == "__main__":
    main()
